function [gr_evol, X_evol, P_evol] = shoot_and_flow(X,P,defo,gr)
%Compute:
%(1). Forward integration of the Hamiltonian flow from initial coupled configuration of varifold/momentums.
%(2). The evolution of the point set gr under the flow generated by X/P.
%
% Input :
%  X.center : initial coordinates of the points (position) in a (n x d) matrix.
%  X.vector : a cell contains first  and second vectors of the initial 2-vector.
%  P.center : is a (n x d) matrix containing the initial spatial momentums.
%  P.vector : a cell contains initial momentums about first  and second vectors of the 2-vector..
%  defo : structure containing the parameters of deformations (kernel_size_mom,method,nstep,...)
%  gr: pts to be transported by the flow
%
% Output:
%  gr_evol: a cell list containing evolution path of gr
%  X_evol.center : a cell list containing evolution path of X.center ( points_evol{i} is a n x d matrix and i ranges from 1 to defo_options.nstep+1)
%  X_evol.vector{i} : a cell containing evolution of X.vector{i}
%  P_evol.center : a cell list containing evolution path of spatial momentums ( nomentums_evol{i} is a n x d matrix and i ranges from 1 to defo_options.nstep+1)
%  P_evol.vector{i} : a cell containing evolution of momentums aboutX.vector{i}

    if isfield(defo,'action') == 0
        defo.action='pushforward';
    end
    
    [X_evol,P_evol]=forward(X,P,defo);
    [gr_evol]=flow(gr,X_evol,P_evol,defo,1);

end